theme = "spacebones_light"

[editor]
auto-save = false

[keys.normal]
"C-s" = ":w"
"C-," = ":open ~/.config/helix/config.toml"
"C-o" = "file_picker_in_current_directory"
"C-z" = "undo"
"C-S-z" = "redo"
"C-c" = "yank"
"C-x" = "delete_selection" # auto yank
"C-v" = "paste_after"
"tab" = "indent"
"S-tab" = "unindent"
"C-f" = "search"
"C-g" = "goto_definition"
"C-S-g" = "goto_reference"
"C-|" = "vsplit"
"C-_" = "hsplit"
"C-w" = "wclose"
"C-d" = ["search_selection", "split_selection"]
"C-a" = "goto_line_start"
"C-e" = "goto_line_end_newline"
"home" = "goto_line_start"
"end" = "goto_line_end_newline"
"pageup" = "page_cursor_half_up"
"pagedown" = "page_cursor_half_down"

[keys.normal."C-b"]
"|" = "vsplit"
"_" = "hsplit"
"left" = "jump_view_left"
"right" = "jump_view_right"
"down" = "jump_view_down"
"up" = "jump_view_up"

[keys.insert]
"C-s" = ["normal_mode", ":w", "insert_mode"]
"C-," = ["normal_mode", ":open ~/.config/helix/config.toml", "insert_mode"]
"C-o" = ["normal_mode", "file_picker_in_current_directory", "insert_mode"]
"C-z" = ["normal_mode", "undo", "insert_mode"]
"C-S-z" = ["normal_mode", "redo", "insert_mode"]
"C-c" = ["normal_mode", "yank", "insert_mode"]
"C-x" = ["normal_mode", "delete_selection", "insert_mode"] # auto yank
"C-v" = ["normal_mode", "paste_after", "insert_mode"]
"tab" = ["normal_mode", "indent", "insert_mode"]
"S-tab" = ["normal_mode", "unindent", "insert_mode"]
"C-f" = ["normal_mode", "search", "insert_mode"]
"C-g" = ["normal_mode", "goto_definition", "insert_mode"]
"C-S-g" = ["normal_mode", "goto_reference", "insert_mode"]
"C-|" = ["normal_mode", "vsplit", "insert_mode"]
"C-_" = ["normal_mode", "hsplit", "insert_mode"]
"C-w" = ["normal_mode", "wclose", "insert_mode"]
"C-a" = ["normal_mode", "goto_line_start", "insert_mode"]
"C-e" = ["normal_mode", "goto_line_end_newline", "insert_mode"]
"C-d" = ["normal_mode", "split_selection", "insert_mode"]

[keys.insert."C-b"]
"|" = ["normal_mode", "vsplit", "insert_mode"]
"_" = ["normal_mode", "hsplit", "insert_mode"]
"left" = ["normal_mode", "jump_view_left", "insert_mode"]
"right" = ["normal_mode", "jump_view_right", "insert_mode"]
"down" = ["normal_mode", "jump_view_down", "insert_mode"]
"up" = ["normal_mode", "jump_view_up", "insert_mode"]
