if has("syntax")
    syntax on
endif

set mouse=a " enable mouse

"Works in normal mode, must press Esc first"
map <C-s> :w<kEnter> 
"Works in insert mode, saves and puts back in insert mode"
imap <C-s> <Esc>:w<kEnter>i

set autoindent
set cindent

set ts=4
set shiftwidth=4
set expandtab

set noswapfile
set number

set incsearch  " incremental search
set hlsearch  " hight search results

colorscheme delek

call plug#begin('~/.vim/plugged')
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
Plug 'deoplete-plugins/deoplete-jedi'
call plug#end()

let g:deoplete#enable_at_startup = 1
let g:python3_host_prog = system('echo -n $(which python3)') " expand('/usr/bin/python3')
let g:deoplete#sources#jedi#show_docstring = 1
