source $HOME/.slimzsh/slim.zsh

for config_file (${ZDOTDIR:-$HOME}/.zsh/zsh.d/*.zsh(N)) source $config_file

# user setting
if [ -e ${HOME}/.setting ]; then
	source ${HOME}/.setting
fi

unsetopt correct_all

bindkey "[D" backward-word
bindkey "[C" forward-word
bindkey "^[[1;2D" backward-word
bindkey "^[[1;2C" forward-word

