export ZSH="${HOME}/.oh-my-zsh"

ZSH_THEME="kafeitu"

plugins=(git z)

source $ZSH/oh-my-zsh.sh

for config_file (${ZDOTDIR:-$HOME}/.zsh/zsh.d/*.zsh(N)) source $config_file

# user setting
if [ -e ${HOME}/.setting ]; then
	source ${HOME}/.setting
fi
